### ISSUE TITLE
ERROR Exeption  Thrown after new maj 13.02.2016

### ISSUE THREAD

**Issue by Asfalt-FR** [wackerl91/luna#40]
Hello, after newmaj today, i have a error...

09:12:10 388.620422 T:1734120480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named dateutil.parser
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 9, in <module>
                                                plugin = bootstrapper.bootstrap()
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/config/bootstrap.py", line 11, in bootstrap
                                                provider.init_di()
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/config/features.py", line 13, in init_di
                                                from resources.lib.scraper.igdbscraper import IgdbScraper
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/scraper/igdbscraper.py", line 5, in <module>
                                                import dateutil.parser as date_parser
                                            ImportError: No module named dateutil.parser
                                            -->End of Python script error report<--
09:12:10 388.788666 T:1958433328   ERROR: GetDirectory - Error getting plugin://script.luna/
09:12:10 388.789032 T:1958433328   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.luna/) failed
09:12:10 388.806580 T:1734120480  NOTICE: Thread BackgroundLoader start, auto delete: false
09:13:33 471.282349 T:1958433328  NOTICE: Samba is idle. Closing the remaining connections
09:13:57 495.791687 T:1723855904  NOTICE: Thread JobWorker start, auto delete: true
09:13:57 495.817108 T:1707078688  NOTICE: Thread BackgroundLoader start, auto delete: false
09:13:57 495.820404 T:1734120480  NOTICE: Thread JobWorker start, auto delete: true
09:13:59 497.658478 T:1707078688  NOTICE: Previous line repeats 1 times.
09:13:59 497.658691 T:1707078688  NOTICE: Thread BackgroundLoader start, auto delete: false
09:14:44 542.190308 T:1715467296  NOTICE: Previous line repeats 2 times.
09:14:44 542.190918 T:1715467296  NOTICE: Thread LanguageInvoker start, auto delete: false
09:14:44 542.392822 T:1540355104  NOTICE: Thread BackgroundLoader start, auto delete: false
09:14:44 542.680664 T:1715467296  NOTICE: -->Python Interpreter Initialized<--
09:14:46 544.379822 T:1715467296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named dateutil.parser
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/luna-master/addon.py", line 9, in <module>
                                                plugin = bootstrapper.bootstrap()
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/config/bootstrap.py", line 11, in bootstrap
                                                provider.init_di()
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/config/features.py", line 13, in init_di
                                                from resources.lib.scraper.igdbscraper import IgdbScraper
                                              File "/home/osmc/.kodi/addons/luna-master/resources/lib/scraper/igdbscraper.py", line 5, in <module>
                                                import dateutil.parser as date_parser
                                            ImportError: No module named dateutil.parser
                                            -->End of Python script error report<--

**Comment by wackerl91** [comment]
Heya @Asfalt-FR,
that's already stated in the [release notes of 0.5.0](https://github.com/wackerl91/luna/releases/tag/v0.5.0-alpha):
```
Known Issues:

Luna might crash instantly after applying this update (dependencies have changed).
If this is the case for you just uninstall and reinstall using attached zip.
```
Reason for this is that I need a date parser for the newly added IGDB scraper and Luna's update process can't handle changed dependencies, so it's just missing on your system - which in return causes Luna to crash.

To resolve this simply go to programs > select Luna > open the context menu > add-on information > uninstall, download script.luna-0.5.0-alpha.zip to the machine running OSMC and reinstall it using this file.

**Comment by Asfalt-FR** [comment]
Sorry...
Ok thx !!!
