### ISSUE TITLE
Try and catch for Scraping

### ISSUE THREAD

**Issue by chrigg** [wackerl91/luna#44]
Just a little thing, maybe a try and catch loop for the first time scraping the games, because when the pc is off while scraping there's a divided by zero error.

**Comment by wackerl91** [comment]
Thanks for the report!
All of the scrapers need better error handling anyway, so I'll take care of all of this together (might be done by tomorrow) as it is closely related.

**Comment by wackerl91** [comment]
This has been resolved by #46 and is part of Luna 0.5.1 release ( #47 ).
If you should have any more suggestions (and / or if you happen to find more bugs) just let me know!
