### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by amivit** [wackerl91/luna#55]
Luna installed from zip perfectly fine on my OSMC 2016.01-1. However now I had to do a fresh install and put the latest 2016.02-3 OSMC on my SD-card. For some reason I can't install luna now. I get a weird dependency error, something about script.module.dateutil 2.4.2, even after doing a full apt-get update && dist-upgrade, and installing moonlight-embedded. Google brought me here, but I don't know how to manually install this library: https://github.com/Razzeee/script.module.dateutil

**Comment by wackerl91** [comment]
Thanks for the report. I'll need to have a look at this with a fresh OSMC installation using your specific version (and for that I'll need to find another SD Card, as my installation is used heavily). Well let you know once I find something.
If anyone else runs into the same issue with the same or other OSMC versions please let me know here.

**Comment by jaketk** [comment]
Same issue with the latest image

**Comment by wackerl91** [comment]
My spare SD card has arrived today and I did a fresh install using the latest OSMC version 2016.02-3 (as stated above by @amivit).
Installing from zip for every addon I'm using failed, so I suspected there was something wrong in general and not only with Luna.
I then wanted to try installing an add-on from the official Kodi repo. As soon as I entered the add-on list it started updating a bunch of pre-installed stuff. After this was done I was able to install Luna perfectly fine. My guess is that on fresh installs the list of items in the repository isn't built properly / at all so you have to trigger a repository update manually by listing the add-ons.

Essentially this means that there's nothing I can do about this as this is (probably) a bug in OSMC's installation procedure (given that it didn't happen in earlier versions). You can easily fix it on your own though:
- go to System -> Add-ons -> Install from Repository -> select the official Kodi repo
- wait for it to update all the pre-installed addons (my Pi became more or less unresponsive during this)
- go back and install Luna from zip, it should be able to find all the dependencies now

If this doesn't work please re-open this issue and if you should run into any other problems using Luna on the latest OSMC version please open separate issues (sadly I don't have the time right now to do a full test).

Cheers!
