### ISSUE TITLE
Not pairing correctly, nor am i able to set a controller map

### ISSUE THREAD

**Issue by Langoor2** [wackerl91/luna#70]
It shows up with "check log for more information..." while trying to pair or set controller mapping (OSMC and newest versions of Luna/Moonlight-embedded) @ Raspberry pi 2 B

**Comment by wackerl91** [comment]
Heya @Langoor2,

could you please paste the relevant portions of the log file? Like any other plugin, Luna is logging directly to the kodi log which can usually be found here: `~/.kodi/temp/kodi.log`. If the relevant portion is really long please consider using pastebin and just post the link.

Thanks!

**Comment by Langoor2** [comment]
Helllo @wackerl91, thanks for your response,

I hope this is the correct part...
`23:41:45 124128.148438 T:1574958064  NOTICE: [script.luna] [CoreService] - initialized
23:41:46 124129.359375 T:1574958064   ERROR: /home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
                                              InsecureRequestWarning)
23:41:46 124129.390625 T:1574958064  NOTICE: [script.luna] Trying to re-encode received XML as UTF-16
23:41:46 124129.406250 T:1574958064   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.etree.ElementTree.ParseError'>
                                            Error Contents: not well-formed (invalid token): line 1, column 1
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.luna/addon.py", line 203, in <module>
                                                game_controller.get_games()
                                              File "/home/osmc/.kodi/addons/script.luna/resources/lib/controller/gamecontroller.py", line 18, in get_games
                                                game_list = self.moonlight_helper.list_games()
                                              File "/home/osmc/.kodi/addons/script.luna/resources/lib/util/moonlighthelper.py", line 135, in list_games
                                                return RequiredFeature('nvhttp').request().get_app_list()
                                              File "/home/osmc/.kodi/addons/script.luna/resources/lib/nvhttp/nvhttp.py", line 146, in get_app_list
                                                applist = self.get_app_list_from_string(response.content)
                                              File "/home/osmc/.kodi/addons/script.luna/resources/lib/nvhttp/nvhttp.py", line 151, in get_app_list_from_string
                                                applist_root = ET.ElementTree(ET.fromstring(self.re_encode_string(xml_string))).getroot()
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
                                                parser.feed(text)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
                                                self._raiseerror(v)
                                              File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
                                                raise err
                                            ParseError: not well-formed (invalid token): line 1, column 1
                                            -->End of Python script error report<--
23:41:46 124129.593750 T:1956901808   ERROR: GetDirectory - Error getting plugin://script.luna/
23:41:46 124129.593750 T:1956901808   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.luna/) failed`

**Comment by wackerl91** [comment]
@Langoor2, looks like this is the same issue as #71.
I'll have a look at it as soon as I can.

**Comment by Langoor2** [comment]
Awesome, thanks! 
I'll try the other version! :)

**Comment by wackerl91** [comment]
@Langoor2 
Sorry for me answering so late, it's been a busy week. Glad the older version is working properly for you. I'll close this issue since it's exactly the same as #71; if I should need any more input I'll mention you over there.
Thanks again for reporting!
(P.S.: I got exams upcoming, that's why I'm really slow at fixing stuff right now. Sorry :/ )
