### ISSUE TITLE
Cant set surround sound

### ISSUE THREAD

**Issue by Direcka** [wackerl91/luna#73]
Im really missing option, to set soundcard to surround sound. Few versions ago its worked automaticaly, after ive configured ALSA, now i have option to choice sound card, but it runs only in 2.0 mode.

**Comment by wackerl91** [comment]
@Direcka 
Just to confirm that it's an issue with Luna, could you try launching the stream from command line (passing your arguments manually) and see if it's working?
Don't own a audio receiver and my TV only supports 2.0 as output, so this is literally impossible for me to test.

**Comment by wackerl91** [comment]
@Direcka 
Just stumbled upon this issue:
https://github.com/irtimmer/moonlight-embedded/issues/365#issuecomment-211392643
It looks like this might be related to what you're seeing.
As said before, I have no way to test this on my own :/

**Comment by Direcka** [comment]
Im sorry for late answer, i was out of home :) Ive tested it today from command line and it doesnt work. So pobably it's realy moonlight/driver problem.
