### ISSUE TITLE
Change TV refresh rate before launching game stream

### ISSUE THREAD

**Issue by brainstormi** [wackerl91/luna#77]
Hi...
   There are many users that setup Kodi screen as PAL, mostly Europeans and Brazilians. Live TV in PAL countries runs in 50Hz(25Hz), this is the reason why in Kodi we setup 50hz in settings. If not, each time you stream a TV channel there is the usual annoying black screen of the TV trying to change refresh rate from 60Hz to 50Hz.
    Is there any way to force TV refresh in Luna to 60Hz before launching moonlight-embedded and restore it once closed, before restarting kodi again?. If not, do you think it would be possible to support some kind of pre/post init scripts in Luna's settings pointed to user defined files, allowing the user to adapt its setup before launching the game stream. This same idea was also applied in Steam Launcher addon for the same purposes:
http://forum.kodi.tv/showthread.php?tid=157499
Regards,

**Comment by wackerl91** [comment]
Heya!
I'll have a look at this soon-ish and see if I can support this behaviour (at least experimentally at first).
Also, having the option to assign pre / post scripts is a great idea and I'll definitely see what I can do about that as well.

Thanks for your suggestion!

**Comment by wackerl91** [comment]
@brainstormi 
Support for pre/post scripts has been added a while ago now. I don't think that I will do the Pi specific way to change refresh rates as this would further limit portability. Instead, every (advanced) user can do this on his own using the system in place (which already was a useful addition, thanks for the suggestion!)
