### ISSUE TITLE
In GFE added games are not be listed in Luna, but in moonlight itself

### ISSUE THREAD

**Issue by sapkra** [wackerl91/luna#78]
You can add custom games to Geforce Experience. But Luna doesn't list it. But I tested it with SSH: moonlight can list this game.

**Comment by wackerl91** [comment]
Works perfectly fine for me.
Did you call the 'update' function (can be found in the context menu of the game list) after adding the game in GFE? Luna doesn't automatically update the game list right now, this needs to be triggered manually.
If you did, can you provide some additional information, like the name of the game, steps to reproduce, ... ?

**Comment by wackerl91** [comment]
Closed because:
* I can't reproduce this
* there was no more information posted regarding this issue after a month

If someone stumbles upon this in the future, feel free to reopen this issue but make sure to provide some additional information. Thanks!
