### ISSUE TITLE
Add support for surround (moonlight stream -surround)

### ISSUE THREAD

**Issue by heydude1337** [wackerl91/luna#80]
Thanks for writing a great plugin. Would it be possible to add surround sound? Moonlight embedded can be started with a -surround flag. Doing this from the command line enables surround for me indeed.

**Comment by wackerl91** [comment]
#73

**Comment by wackerl91** [comment]
Given that someone else already reported the very same issue and couldn't get it to work using command line, I'm somewhat curious what versions of moonlight / GFE you're using. This information might also help out the guy in the other issue.

That being said I'll make sure to support this in the next major update (no ETA though).

**Comment by heydude1337** [comment]
moonlight embedded v2.2.0
GFE 3.0.6.49

hacking your launch scripts with a forced -surround flag works for me.

**Comment by wackerl91** [comment]
Good to hear you found a solution that works for you for now and thanks for letting me know!
It will still be part of the next update which will also overwrite your changed launch scripts, so make sure to enable it in Luna's settings once a new version is available ;-)

**Comment by wackerl91** [comment]
Will be part of the 0.7.0. release, see #86

**Comment by wackerl91** [comment]
@heydude1337 
Just as a side note, you will need to give this a try as soon as the next version has been released. I got no means of testing this on my end (no surround attached to my TV).
As always, your feedback will be appreciated!
