### ISSUE TITLE
Question: How to use with Chrome Moonlight

### ISSUE THREAD

**Issue by roemhildtg** [wackerl91/luna#82]
Sorry, I'm completely new to moonlight and this launcher. Basically, I have a small intel computer running xubuntu, and I have moonlight installed as a chrome addon. Can this set up work with luna?

**Comment by wackerl91** [comment]
@roemhildtg 
Sorry for my late reply.
Most likely this won't work. While you could probably get it to launch, there's no way to launch a specific game, let alone make it read the config dumped by Luna (I guess I could find and replace the addons config file, but that's just too much pain).
Basically I'd need a way to pass options to moonlight via command line, which I can't see happening here.

**Comment by roemhildtg** [comment]
Okay, gotcha. This is probably more of a question for https://github.com/irtimmer/moonlight-embedded but do you know if its possible to use luna on an intel x64 cpu?

**Comment by wackerl91** [comment]
Luna will run on anything where Kodi is available ;)
I'm unsure if anyone over at moonlight-embedded is able to help you, since it seems to be a strict ARM port. But maybe they can point you into the right direction.

**Comment by roemhildtg** [comment]
Sounds good. Thank you :)

**Comment by wackerl91** [comment]
You're welcome. Well, and sorry I wasn't too much of a help with your current problem :/

Let me know if you're running into any Luna specific issues on your hardware and I'll try to resolve them (if there are any). I've been running it on OSX while developing it and was fine for the most part (except for some Linux specific stuff in there).

**Comment by roemhildtg** [comment]
No worries, I appreciate the quick response and your willingness to help. I'm just not sure how to get started with the nvidia game streaming. I had previously used steam streaming, but have since bought a nvidia card and wanted to try it out.
