### ISSUE TITLE
Add support for new moonlight-chrome  (PC is deprecated)

### ISSUE THREAD

**Issue by Panderine** [wackerl91/luna#84]
With PC version deprecated moonlight-chrome is the only way to use moonlight on a non-embedded device. Please make luna able to launch that from Kodi !. Thanks!

**Comment by wackerl91** [comment]
@Panderine 
Related: https://github.com/wackerl91/luna/issues/82
The gist is: I had a quick look at this back then and couldn't find a way to pass CLI arguments to chrome addons (even launching them from command line is hard enough).

If anyone can think of a way to make this happen I'm more than happy to oblige. Until then there's nothing I can do really ...

**Comment by wackerl91** [comment]
It seems to be possible to pass a file to a chrome app: [SO Post](http://stackoverflow.com/questions/19227472/how-to-open-a-chrome-packaged-app-with-a-parameter-on-windows). However, moonlight-chrome would need to support that behaviour and from what I can see by looking at their manifest.json it currently doesn't.
